name: ESLint
run-name: Push from: ${{ github.actor }}. Running ESLint
on:
  push:
    branches:
      [ $default-branch, $protected-branch ]
    pull_request:
      branches: [ $default-branch ]
jobs:
  es-lint:
    name: Run ESLint scanning
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Initialize npm
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
        run: npm init -y

      - name: Install ESLint
        run: |
          npm init @eslint/config --config semistandard

      - name: Run ESLint
        run: npx eslint .
          --ext .js,.jsx,.ts,.tsx
          --output-file eslint-results.sarif
        continue-on-error: true

      - name: Upload analysis results to Github
        uses: github/codeq1-action/upload-sarif@v2
        with:
          sarif_file: eslint-results.sarif
          wait-for-processing: true
